quarkus.http.port=8081

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
%prod.quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://postgres:5432/inventorydb}

quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.schema-management.strategy=validate

mp.messaging.incoming.order-created.connector=smallrye-kafka
mp.messaging.incoming.order-created.topic=order-events
mp.messaging.incoming.order-created.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.order-created.auto.offset.reset=earliest
mp.messaging.incoming.order-created.group.id=inventory-service
%prod.kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

quarkus.log.category."dev.pedro.outbox.inventory".level=INFO
